
tasklist:
  client:
    profile: oidc
    base-url: https://parand.mparsict.com
    auth-url: https://keycloack.parand.mparsict.com/auth/realms/camunda-platform/protocol/openid-connect/token
    client-id: orchestration
    client-secret: secret
    audience: orchestration

camunda:
  webhook:
    url: http://46.245.79.18:8086/inbound
    authorization:
      username: "semati"
      password: "semati"
  client:
    mode: self-managed
    grpc-address: http://46.245.79.18:26500
    rest-address: https://parand.mparsict.com
    enabled: true
server:
  port: 8020